/**
 * Admin paneliga xos qo'shimcha matnlar (uz lotin, ’ U+2019).
 * `src/i18n/uz.ts` da bo'lmagan kalitlar shu yerda.
 */
export const A = {
  shell: {
    open: 'Ochish',
    search: 'E’lon, buyurtma yoki foydalanuvchi…',
    searchShort: 'Qidirish…',
    searchHint: 'ID yoki nom bo’yicha',
    noResults: 'Hech narsa topilmadi',
    listings: 'E’lonlar', orders: 'Buyurtmalar', users: 'Foydalanuvchilar', sections: 'Bo’limlar', actions: 'Amallar', roles: 'Rolni almashtirish',
    notifications: 'Bildirishnomalar',
    noNotifications: 'Yangi hodisa yo’q',
    switchRole: 'Rolni almashtirish',
    shortcuts: 'Klaviatura tugmalari',
    shortcutHint: '? — tugmalar ro’yxati',
    collapse: 'Menyuni yig’ish', expand: 'Menyuni yoyish',
    demoClock: 'Demo vaqti',
    openListing: 'E’lon #L-58213 ni och',
    goPricing: 'Narx tahliliga o’t',
    goSection: '{s} bo’limiga o’t',
    to17: 'Soat 17:00 ga o’tkaz',
    plusDay: '+1 kun',
    payday: 'Juma to’lovi',
    dark: 'Tungi rejim',
    roleTo: 'Rolni almashtirish: {r}',
    noAccessHint: 'Joriy rol: {r}. Boshqa rolga o’tish uchun yuqori o’ngdagi avatarni bosing.',
    loadError: 'Bo’limni yuklashda xatolik',
    kbd: {
      palette: 'Buyruqlar palitrasi', help: 'Tugmalar ro’yxati', next: 'Keyingi e’lon', prev: 'Oldingi e’lon',
      approve: 'Tasdiqlash', edit: 'Tahrir so’rash', reject: 'Rad etish', esc: 'Yopish',
    },
  },
  common: {
    id: 'ID', date: 'Sana', time: 'Vaqt', status: 'Holat', region: 'Viloyat', branch: 'Filial', seller: 'Sotuvchi', buyer: 'Xaridor',
    price: 'Narx', amount: 'Summa', total: 'Jami', actions: 'Amallar', note: 'Izoh', reason: 'Sabab', title: 'Nomi', category: 'Kategoriya',
    all: 'Hammasi', today: 'Bugun', filter: 'Filtr', clear: 'Tozalash', save: 'Saqlash', saved: 'Saqlandi', apply: 'Qo’llash',
    details: 'Tafsilotlar', open: 'Ochish', close: 'Yopish', cancel: 'Bekor qilish', confirm: 'Tasdiqlash', add: 'Qo’shish', edit: 'Tahrirlash',
    sample: 'namuna', loading: 'Yuklanmoqda…', empty: 'Hozircha bo’sh', emptyHint: 'Filtrlarni o’zgartirib ko’ring.',
    myQueue: 'Mening navbatim', savedViews: 'Saqlangan ko’rinishlar', saveView: 'Ko’rinishni saqlash', viewName: 'Ko’rinish nomi',
    selected: '{n} ta tanlandi', items: '{n} ta tovar', pcs: 'dona', hours: 'soat', minutes: 'daq', days: 'kun',
    ago: '{t} oldin', justNow: 'hozirgina', waiting: 'kutmoqda',
    from: 'dan', to: 'gacha', yes: 'Ha', no: 'Yo’q', unknown: '—',
    source: { listing: 'E’lon', product: 'Mall' },
    escrow: { none: 'Escrow yo’q', held: 'Escrow ushlangan', released: 'Escrow yechilgan', refunded: 'Qaytarilgan', partially_refunded: 'Qisman qaytarilgan' },
    company: { wholesale: 'Ulgurji', warehouse: 'Omborda', self_ship: 'O’zi jo’natadi' },
    companyStatus: { active: 'Faol', onboarding: 'Ulanmoqda', suspended: 'To’xtatilgan' },
    productCheck: { passed: 'O’tdi', overpriced: 'Qimmat', pending: 'Kutilmoqda' },
    payment: { payme: 'Payme', click: 'Click', cash: 'Naqd' },
    delivery: { bts_branch: 'BTS filiali', courier_tashkent: 'Kuryer (Toshkent)', pickup: 'O’zi olib ketadi' },
    txKind: { payment_in: 'Kirim', payout: 'To’lov', refund: 'Qaytarish', boost: 'Ko’tarish', commission: 'Komissiya' },
    txStatus: { ok: 'Muvaffaqiyatli', pending: 'Kutilmoqda', failed: 'Xato' },
    campaignKind: { push: 'Push', banner: 'Banner' },
    campaignStatus: { draft: 'Qoralama', sent: 'Yuborilgan' },
    role: 'Rol', verified: 'Tekshirilgan', blocked: 'Bloklangan', active: 'Faol',
    errorAction: 'Amal bajarilmadi',
  },
  dashboard: {
    salesToday: 'Bugungi savdo', orders: 'Buyurtmalar', newListings: 'Yangi e’lonlar', commission: 'Komissiya', review: 'O’rtacha tekshiruv',
    vsTarget: 'maqsadga nisbatan', chart14: 'So’nggi 14 kun savdosi', mall: 'Mall', listings: 'E’lonlar',
    regions: 'Viloyatlar bo’yicha (14 kun)', share: 'Ulush', sales: 'Savdo', topCats: 'Top kategoriyalar (30 kun)', sold: 'sotildi',
    attention: {
      moderation: 'Moderatsiyada kutayotgan e’lonlar', pricing: 'Narx tekshiruvidagi e’lonlar', fees: 'Tasdiqlanmagan xizmat haqlari',
      logistics: 'Qadoqlanmagan yuklar', returns: 'Ochiq qaytarish so’rovlari', payments: 'Kutilayotgan to’lovlar', products: 'Narx qoidasidan o’tmagan tovarlar',
    },
    allClear: 'Hammasi joyida — navbatlar bo’sh',
  },
  moderation: {
    queue: 'Navbat', empty: 'Moderatsiya navbati bo’sh', emptyHint: 'Yangi e’lonlar kelganda shu yerda ko’rinadi.',
    banned: 'Taqiqlangan so’zlar', bannedFound: '{n} ta taqiqlangan so’z', aiFlags: 'AI belgilari', risks: 'Xavf belgilari',
    specs: 'Aniqlangan xususiyatlar', imei: 'IMEI', images: 'Rasmlar', original: 'original', notOriginal: 'shubhali (internetdan)',
    confidence: 'ishonch', noRisks: 'Xavf topilmadi', lowConfidence: 'AI ishonchi past', priceFlag: 'Narx: {f}',
    description: 'Tavsif', zoom: 'Rasmni kattalashtirish', approved: 'E’lon tasdiqlandi', returned: 'Tahrirga qaytarildi', rejected: 'E’lon rad etildi',
    editReason: 'Sotuvchiga nima tuzatish kerakligini yozing', rejectReason: 'Rad etish sababi (sotuvchi ko’radi)',
    selectHint: 'Chapdan e’lonni tanlang yoki J/K tugmalarini bosing',
  },
  pricing: {
    queue: 'Navbat', chips: { all: 'Hammasi', overpriced: 'Qimmat', fair: 'Mos', low_data: 'Kam ma’lumot', imei_issue: 'IMEI muammo' },
    empty: 'Narx navbati bo’sh', emptyHint: 'Sotuvchi yangi e’lon yuborganda shu yerda paydo bo’ladi.',
    asking: 'Sotuvchi narxi', specs: 'AI aniqlagan xususiyatlar', comparables: '30 kunlik o’xshash e’lonlar', newRetail: 'Yangi narx (do’konlar)',
    histogram: 'Narxlar taqsimoti', outcome: { sold: '{n} kunda sotildi', stale: '{n} kun sotilmadi', active: 'faol' },
    aiCard: 'AI tahlili', confidence: 'Ishonch', ledger: 'Hisob-kitob', suggested: 'Tavsiya etilgan narx', factors: 'Omillar ta’siri',
    moderatorPrice: 'Moderator narxi', fee: 'Xizmat haqi', sellerGets: 'Sotuvchiga tegadi', note: 'Sotuvchiga izoh', notePlaceholder: 'Nega shu narx? Sotuvchi shu izohni ko’radi',
    minus: '−50 000', plus: '+50 000', runAi: 'AI tahlilini ishga tushirish', noSuggestion: 'AI tahlili hali yo’q',
    sent: 'Taklif yuborildi', sentBody: '{t} — {p}', vsAi: 'AI’ga nisbatan', vsAsk: 'so’ralganga nisbatan', weight: 'vazn', waiting: 'kutmoqda',
    marketMedian: 'Bozor mediani (A)', noComparables: 'O’xshash e’lonlar topilmadi', condition: 'Holat', imeiStatus: { clean: 'IMEI toza', suspicious: 'IMEI shubhali', not_provided: 'IMEI kiritilmagan' },
    editSpec: 'Tahrirlash', specSaved: 'Xususiyat yangilandi', returnReason: 'Qaytarish sababi', rejectReason: 'Rad etish sababi',
    sellerNote: 'Sotuvchi tavsifi',
  },
  fees: {
    rules: 'Qoidalar', published: 'E’lon qilingan', draft: 'Qoralama', archived: 'Arxiv', version: 'Versiya', v: 'v{n}',
    range: 'Narx oralig’i', type: 'Turi', value: 'Qiymat', cap: 'Chegara', category: 'Kategoriya', default: 'Umumiy',
    types: { fixed: 'Qat’iy', percent: 'Foiz', percent_capped: 'Foiz (chegarali)' },
    tryIt: 'Sinab ko’rish', tryPrice: 'Tovar narxi', effective: 'Amaldagi foiz', rule: 'Qoida',
    editDraft: 'Qoralamani tahrirlash', saveDraft: 'Qoralama saqlash', publish: 'E’lon qilish', addRule: 'Qoida qo’shish', removeRule: 'Qoidani o’chirish',
    draftNote: 'Qoralama izohi', history: 'Versiyalar tarixi', approvals: 'Haq tasdiqlash', approveSel: 'Tanlanganlarni tasdiqlash',
    approve: 'Tasdiqlash', adjust: 'O’zgartirish', autoFee: 'Avto haq', finalFee: 'Yakuniy haq', newFee: 'Yangi haq', adjustReason: 'O’zgartirish sababi',
    approved: 'Haq tasdiqlandi', adjusted: 'Haq o’zgartirildi', savedDraft: 'Qoralama saqlandi', publishedToast: 'Qoidalar e’lon qilindi',
    infinity: '∞', sampleHint: 'Raqamlar namuna — investor demo uchun', emptyApprovals: 'Tasdiqlash navbati bo’sh',
  },
  orders: {
    source: 'Manba', items: 'Tovarlar', subOrders: 'Yuklar', escrow: 'Escrow', delivery: 'Yetkazish', payment: 'To’lov', timeline: 'Vaqt chizig’i',
    audit: 'Audit yozuvlari', changeStatus: 'Holatni o’zgartirish', newStatus: 'Yangi holat', cancel: 'Buyurtmani bekor qilish', cancelReason: 'Bekor qilish sababi',
    cancelled: 'Buyurtma bekor qilindi', statusChanged: 'Holat o’zgartirildi', noTransitions: 'Boshqa o’tish yo’q', views: { all: 'Hammasi', today: 'Bugun', escrow: 'Escrow ushlangan', cancelled: 'Bekor qilingan', myQueue: 'Mening navbatim' },
    dateFrom: 'Sanadan', dateTo: 'Sanagacha', fee: 'Komissiya', txId: 'Tranzaksiya', rating: 'Baho',
  },
  logistics: {
    cutoff: '17:00 gacha', left: 'qoldi', closed: 'Partiya yopildi', bts19: 'BTS mashinasi 19:00', packed: 'Qadoqlandi', regions: 'Viloyatlar bo’yicha',
    todays: 'Bugungi yuklar', pack: 'Qadoqlandi', print: 'Yuk xatini chop etish', packSel: 'Tanlanganlarni qadoqlash', waybill: 'Yuk xati',
    manifest: 'Kechki partiya', manifestOpen: 'Ochiq manifest', handToBts: 'Kechki partiyani BTS’ga topshirish', closeManifest: 'Partiyani yopish',
    recent: 'So’nggi partiyalar', packedToast: 'Yuk qadoqlandi', handedToast: 'Partiya BTS’ga topshirildi', closedToast: 'Partiya yopildi',
    printLabel: 'Chop etish', labelTitle: 'A6 yuk xati', empty: 'Bugun yuk yo’q', handHint: '17:00 dan keyin yoki partiya yopilganda faollashadi',
    noManifest: 'Ochiq manifest yo’q', items: 'Tovarlar',
  },
  payments: {
    tabs: { income: 'Kirim', escrow: 'Escrow', payouts: 'Sotuvchilarga to’lovlar', companies: 'Kompaniyalar bilan hisob-kitob' },
    provider: 'Provayder', ref: 'Havola', heldTotal: 'Ushlangan escrow', heldCount: 'Buyurtmalar', card: 'Karta', approvals: 'Tasdiqlar',
    schedule: 'Rejalashtirish', second: 'Ikkinchi tasdiq', pay: 'To’lash', dual: 'qo’sh imzo kerak', sameStaff: 'Boshqa xodim tasdiqlashi kerak',
    payday: 'Juma to’lovi', paydayConfirm: 'Barcha kutilayotgan to’lovlar rejalashtiriladi va to’lanadi. Davom etasizmi?',
    paydayDone: 'Juma to’lovi bajarildi', scheduled: 'Rejalashtirildi', approved: 'Tasdiqlandi', paid: 'To’landi', scheduledFor: 'Sana',
    salesMonth: 'Shu oy savdosi', commission: 'Komissiya', act: 'Akt', actTitle: 'Hisob-kitob akti', orders: 'Buyurtmalar', net: 'Kompaniyaga',
    emptyPayouts: 'To’lovlar yo’q', pendingBadge: 'kutilmoqda',
  },
  returns: {
    sla: 'SLA', decision: 'Qaror', full: 'To’liq', partial: 'Qisman', deny: 'Rad', amount: 'Qaytariladigan summa', noteRequired: 'Qaror izohi (majburiy)',
    escrowEffect: 'Escrow ta’siri', effectFull: '{a} xaridorga qaytariladi, sotuvchiga to’lov bo’lmaydi', effectPartial: '{a} xaridorga qaytariladi, {b} sotuvchiga o’tadi',
    effectDeny: 'Escrow sotuvchiga to’lovga rejalashtiriladi ({a})', images: 'Xaridor rasmlari', sellerReply: 'Sotuvchi javobi', noReply: 'Sotuvchi hali javob bermagan',
    chat: 'Yozishmalar', noChat: 'Yozishma yo’q', decided: 'Qaror qabul qilindi', empty: 'Qaytarish so’rovlari yo’q', overdue: 'muddat o’tdi', open: 'Ochiq', item: 'Tovar',
  },
  companies: {
    model: 'Model', commission: 'Komissiya', rating: 'Reyting', late: 'Kechikish', returns: 'Qaytarish', products: 'Tovarlar', joined: 'Qo’shilgan', contract: 'Shartnoma',
    new: 'Yangi kompaniya', step1: 'INN va nom', step2: 'Shartnoma', step3: 'Model va komissiya', inn: 'INN', name: 'Nomi', file: 'Shartnoma fayli', noFile: 'Fayl tanlanmagan',
    created: 'Kompaniya qo’shildi', statusChanged: 'Holat o’zgartirildi', commissionChanged: 'Komissiya o’zgartirildi', setStatus: 'Holatni o’zgartirish', setCommission: 'Komissiya, %',
    description: 'Tavsif', shipSpeed: 'Jo’natish, kun',
  },
  products: {
    filters: { all: 'Hammasi', failed: 'Narx qoidasidan o’tmagan', lowStock: 'Zaxira tugayotgan' }, company: 'Kompaniya', sku: 'SKU', market: 'Bozor mediani', delta: 'Farq',
    stock: 'Zaxira', check: 'Tekshiruv', pass: 'O’tdi', overpriced: 'Qimmat', checked: 'Tekshiruv natijasi saqlandi', priceVsMarket: 'Narx va bozor', warranty: 'Kafolat, oy', returnDays: 'Qaytarish, kun',
    openCompany: 'Kompaniyani ochish', lowStockBadge: 'kam',
  },
  users: {
    name: 'Ism', rating: 'Reyting', listings: 'E’lonlar', orders: 'Buyurtmalar', complaints: 'Shikoyatlar', verified: 'Tekshirilgan sotuvchi', block: 'Bloklash', unblock: 'Blokdan chiqarish',
    blockReason: 'Bloklash sababi', blocked: 'Foydalanuvchi bloklandi', unblocked: 'Blok olib tashlandi', verifiedToast: 'Tekshirilgan belgisi yangilandi', joined: 'Qo’shilgan', sold: 'Sotgan',
    noListings: 'E’lonlar yo’q', noOrders: 'Buyurtmalar yo’q', noComplaints: 'Shikoyatlar yo’q', phone: 'Telefon', language: 'Til',
  },
  categories: {
    tree: 'Kategoriyalar daraxti', attributes: 'Xususiyatlar', key: 'Kalit', label: 'Nomi', type: 'Turi', options: 'Variantlar', unit: 'Birlik', required: 'Majburiy',
    addAttr: 'Xususiyat qo’shish', conditions: 'Holat shkalasi', discount: 'Sharabara chegirmasi, %', maxNewRatio: 'Yangi narx chegarasi, %', saved: 'Kategoriya saqlandi',
    new: 'Yangi kategoriya', parent: 'Ota kategoriya', root: 'Asosiy (ildiz)', created: 'Kategoriya qo’shildi', listingsCount: '{n} ta e’lon',
    optionsHint: 'Vergul bilan ajrating',
  },
  campaigns: {
    new: 'Yangi kampaniya', kind: 'Turi', title: 'Sarlavha', body: 'Matn', segment: 'Segment', regions: 'Viloyatlar', categories: 'Kategoriyalar', preview: 'Jonli ko’rinish',
    save: 'Saqlash', sendNow: 'Hozir yuborish', sendConfirm: 'Kampaniya barcha mos foydalanuvchilarga yuboriladi. Davom etasizmi?', reach: 'Qamrov', sentAt: 'Yuborilgan',
    saved: 'Kampaniya saqlandi', sent: 'Kampaniya yuborildi', allRegions: 'Barcha viloyatlar', allCats: 'Barcha kategoriyalar', empty: 'Kampaniyalar yo’q', selectHint: 'Kampaniyani tanlang yoki yangisini yarating',
    estimatedReach: 'Taxminiy qamrov', banner: 'Banner', now: 'hozir',
  },
  reports: {
    range: 'Davr', sales: 'Savdo dinamikasi', sources: 'Daromad manbalari', funnel: 'Voronka', speed: 'Moderatsiya tezligi', ai: 'AI aniqligi',
    src: { listingsFee: 'Komissiya — e’lonlar', mallFee: 'Komissiya — Mall', boost: 'Ko’tarish', delivery: 'Yetkazish', ads: 'Reklama' },
    funnelSteps: { view: 'Ko’rish', chat: 'Yozish', cart: 'Savat', purchase: 'To’lov' }, minutes: 'daqiqa', within5: '5% ichida', avgDev: 'O’rtacha farq',
    decisions: 'ta qaror', deviation: 'Farq, %', noData: 'Bu davr uchun ma’lumot yo’q',
  },
  roles: {
    view: 'ko’rish', edit: 'tahrirlash', approve: 'tasdiqlash', locked: 'Super admin huquqlari qulflangan', hint: 'O’zgarishlar darhol yon menyuga ta’sir qiladi', section: 'Bo’lim',
  },
  audit: {
    actor: 'Xodim', kind: 'Turi', entity: 'Obyekt', entityId: 'ID', field: 'Maydon', change: 'O’zgarish', note: 'Izoh', search: 'ID yoki matn bo’yicha qidirish',
    table: 'Jadval', trail: 'Iz', trailTitle: '{id} bo’yicha iz', trailEmpty: 'Bu ID bo’yicha yozuv yo’q', related: 'Bog’liq: {ids}', entries: '{n} ta yozuv',
    kinds: { status: 'Holat', money: 'Pul', price: 'Narx', fee: 'Komissiya', data: 'Ma’lumot', auth: 'Huquq' },
  },
  warehouse: {
    all: 'Hammasi', newProduct: 'Yangi tovar', newReceipt: 'Yangi kirim', pcs: 'dona',
    kpi: { total: 'Jami zaxira', value: 'Zaxira qiymati', low: 'Kam qolgan', inToday: 'Bugun kirim', outToday: 'Bugun chiqim', expected: 'Kutilayotgan kirim', days14: '14 kun', mlrd: 'mlrd' },
    tabs: { stock: 'Zaxira', receipts: 'Kirimlar', sales: 'Sotuvlar bo’yicha', movements: 'Harakatlar' },
    stock: {
      sku: 'SKU', product: 'Tovar', company: 'Kompaniya', warehouse: 'Ombor', qty: 'Zaxira', reserved: 'Band', min: 'Min', sold30: 'Sotildi (30 k)',
      daily: 'Kunlik', daysLeft: 'Yetadi', daysUnit: 'kun', price: 'Narx', low: 'Kam', onlyLow: 'Faqat kam qolgan', search: 'SKU yoki nom…',
      company_all: 'Kompaniya: hammasi', category_all: 'Kategoriya: hammasi', empty: 'Zaxira topilmadi', emptyHint: 'Filtrlarni o’zgartiring yoki yangi tovar qo’shing.',
      levels: 'Omborlar bo’yicha', history: 'Harakatlar tarixi (oxirgi 20)', noHistory: 'Harakatlar yo’q',
      adjust: 'Tuzatish', adjustHint: 'Inventarizatsiya farqi: +/− dona', adjustReason: 'Sabab (majburiy)', adjustReasonPh: 'Masalan: inventarizatsiya, buzilgan tovar…', adjusted: 'Zaxira tuzatildi',
      transfer: 'Ko’chirish', transferTo: 'Qayerga', transferQty: 'Miqdor', transferred: 'Tovar ko’chirildi', sameWarehouse: 'Boshqa omborni tanlang',
      minQty: 'Min miqdor', minSaved: 'Min miqdor saqlandi', readOnly: 'Faqat ko’rish huquqi',
    },
    receipts: {
      invoice: 'Yuk xati №', company: 'Kompaniya', warehouse: 'Ombor', lines: 'Qatorlar', qty: 'Dona', total: 'Summa', status: 'Holat', date: 'Sana',
      statuses: { expected: 'Kutilmoqda', received: 'Qabul qilindi', checked: 'Tekshirildi' },
      thisMonth: 'Bu oy kompaniyalar bo’yicha', noMonth: 'Bu oy kirim bo’lmagan', receive: 'Qabul qilish', check: 'Tekshirildi',
      received: 'Kirim qabul qilindi', checked: 'Kirim tekshirildi', product: 'Tovar', expectedQty: 'Kutilgan', acceptedQty: 'Qabul', unitCost: 'Tannarx', sum: 'Summa',
      note: 'Izoh', expectedAt: 'Kutilgan vaqt', receivedAt: 'Qabul vaqti', checkedBy: 'Tekshirdi', empty: 'Kirimlar yo’q', emptyHint: 'Kompaniyadan yangi kirim yarating.',
      step1: 'Kompaniya va ombor', step2: 'Qatorlar', step3: 'Xulosa', addLine: 'Qator qo’shish', removeLine: 'Qatorni o’chirish', pickProduct: 'Tovarni tanlang',
      noProducts: 'Bu kompaniyada tovar yo’q', created: 'Kirim yaratildi', linesCount: '{n} qator', filterStatus: 'Holat: hammasi',
    },
    sales: {
      byChannel: 'Kanallar bo’yicha chiqim (30 kun)', byRegion: 'Viloyatlar bo’yicha (yetkazilgan)', top: 'Top 15 tovar (30 kun)', channels: 'Kanallar (30 kun)',
      product: 'Tovar', company: 'Kompaniya', sold: 'Sotildi', revenue: 'Tushum', left: 'Qoldiq', share: 'Kanal ulushi', orders: 'buyurtma', pct: 'ulush',
      noSales: 'Bu davrda sotuv bo’lmagan', online: 'Onlayn', other: 'Boshqa',
      channel: { app: 'Ilova', telegram: 'Telegram', instagram: 'Instagram', offline: 'Oflayn' },
    },
    movements: {
      time: 'Vaqt', product: 'Tovar', warehouse: 'Ombor', kind: 'Tur', qty: 'Miqdor', channel: 'Kanal', ref: 'Havola', by: 'Kim', note: 'Izoh',
      kinds: { in: 'Kirim', out: 'Chiqim', adjust: 'Tuzatish', transfer: 'Ko’chirish', return: 'Qaytarish' },
      kind_all: 'Tur: hammasi', channel_all: 'Kanal: hammasi', warehouse_all: 'Ombor: hammasi', system: 'Tizim', empty: 'Harakatlar yo’q', emptyHint: 'Filtrlarni o’zgartiring.',
    },
    product: {
      company: 'Kompaniya', sku: 'SKU', title: 'Nomi', category: 'Kategoriya', price: 'Narx', cost: 'Tannarx', qty: 'Boshlang’ich miqdor', warehouse: 'Ombor', warranty: 'Kafolat, oy',
      created: 'Tovar qo’shildi', skuPh: 'NE-1234', titlePh: 'Masalan: Samsung Galaxy A55 128GB',
    },
  },
} as const

export function tt(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (_, k) => (vars[k] !== undefined ? String(vars[k]) : `{${k}}`))
}
