/** Direktor paneli matnlari (uz lotin, ’ U+2019). */
export const D = {
  title: 'Direktor paneli',
  subtitle: 'Bir ekranda butun biznes',
  greeting: { tong: 'Xayrli tong', kun: 'Xayrli kun', kech: 'Xayrli kech' } as const,
  director: 'Direktor',
  sample: 'namuna',
  period: { bugun: 'Bugun', hafta: 'Hafta', oy: 'Oy' } as const,
  periodLong: { bugun: 'bugun', hafta: 'so’nggi 7 kun', oy: 'so’nggi 30 kun' } as const,
  vsPrev: { bugun: 'kechaga nisbatan', hafta: 'o’tgan haftaga nisbatan', oy: '30 kunlik jami' } as const,
  tabs: { umumiy: 'Umumiy', savdo: 'Savdo', pul: 'Pul', ombor: 'Ombor', muammolar: 'Muammolar' } as const,
  theme: 'Tungi rejim',
  demoClock: 'Demo vaqti',
  all: 'Barchasi',
  empty: 'Hozircha bo’sh',
  open: 'Ochish',
  close: 'Yopish',
  pcs: 'dona',
  orders: 'buyurtma',
  overview: {
    salesHero: { bugun: 'Bugungi savdo', hafta: 'Haftalik savdo', oy: 'Oylik savdo' } as const,
    days14: 'so’nggi 14 kun',
    orders: 'Buyurtmalar',
    avgCheck: 'O’rtacha chek',
    activeListings: 'Faol e’lonlar',
    mallVsListings: 'Mall · E’lonlar',
    mall: 'Mall',
    listings: 'E’lonlar',
    commission: 'Komissiya daromadi',
    escrow: 'Escrow’dagi pul',
    escrowHint: 'xaridor to’lagan, sotuvchiga hali o’tmagan',
    paidOut: { bugun: 'Bugun to’langan', hafta: 'Haftada to’langan', oy: 'Oyda to’langan' } as const,
    paidOutHint: 'sotuvchilarga o’tkazildi',
    channels: 'Kanallar',
    channelsRevenue: 'Kanallar bo’yicha tushum',
    channelsHint: 'savdo qayerdan keldi',
    feed: 'Bugun nima bo’ldi',
    feedHint: 'so’nggi 12 hodisa',
    attention: 'Diqqat',
    attentionOk: 'Hammasi joyida',
    seeAll: 'Hammasini ko’rish',
    issues: '{n} ta masala',
    cashCash: 'Kassa · naqd',
    cashCard: 'Karta · Click/Payme',
    stockAlerts: 'Ombor ogohlantirishlari',
    outOfStock: 'Tugadi',
    waitingOrders: '{n} ta buyurtma kutmoqda',
    leftPcs: '{n} dona qoldi',
    topProducts: 'Top tovarlar',
  },
  channel: { app: 'Ilova', telegram: 'Telegram', instagram: 'Instagram', offline: 'Oflayn' } as const,
  sales: {
    chart30: '30 kunlik savdo',
    byRegion: 'Viloyatlar bo’yicha',
    topProducts: 'Top 10 tovar',
    topCompanies: 'Top 5 kompaniya',
    topSellers: 'Top 5 sotuvchi',
    categories: 'Kategoriyalar ulushi',
    channels: 'Kanallar bo’yicha',
    recentOrders: 'So’nggi buyurtmalar',
    returnRate: 'qaytarish',
    sold: 'sotildi',
    revenue: 'Savdo',
    count: 'Soni',
    share: 'Ulush',
    orderDetail: 'Buyurtma',
    items: 'Tovarlar',
    timeline: 'Yo’l',
    money: 'Pul',
    total: 'Jami',
    delivery: 'Yetkazish',
    fee: 'Komissiya',
    sellerGets: 'Sotuvchiga',
    buyer: 'Xaridor',
    channel: 'Kanal',
    payment: 'To’lov',
    openInAdmin: 'Admin panelda ochish',
  },
  money: {
    income: 'Kirim',
    incomeHint: 'xaridorlar to’lovi',
    escrow: 'Escrow',
    escrowHint: 'ushlab turilgan',
    outcome: 'Chiqim',
    outcomeHint: 'sotuvchilarga to’lovlar',
    commission: 'Komissiya',
    refunds: 'Qaytarilgan',
    boost: 'E’lon ko’tarish',
    net: 'Sof daromad',
    netFormula: 'Sof daromad = komissiya + e’lon ko’tarish − qaytarilgan buyurtmalar bo’yicha yo’qotilgan komissiya. Raqamlar namuna.',
    cashflow: 'Pul oqimi · 30 kun',
    cashIn: 'Kirim',
    cashOut: 'Chiqim',
    awaiting: 'To’lovni kutayotganlar',
    awaitingHint: 'sotuvchi va kompaniyalar',
    settlement: 'Kompaniyalar bilan hisob-kitob',
    company: 'Kompaniya',
    sales: 'Savdo',
    toPay: 'To’lanadi',
    pending: 'Navbatda',
    secondApproval: 'Qo’sh imzo',
    card: 'karta',
  },
  stock: {
    totalQty: 'Jami zaxira',
    totalValue: 'Zaxira qiymati',
    valueHint: 'sotuv narxida',
    skus: 'nom tovar',
    warehouses: 'Omborlar',
    fill: 'to’lganlik',
    low: 'Kam zaxira',
    lowHint: 'minimal darajaga tushgan',
    daysLeft: '{n} kunga yetadi',
    daysLeftNone: 'sotuv yo’q',
    daysLeftToday: '1 kundan kam',
    incoming: 'Kutilayotgan kirimlar',
    todayIn: 'Bugun kirim',
    todayOut: 'Bugun chiqim',
    topMoving: 'Eng ko’p ketayotgan',
    topMovingHint: '30 kunda chiqim, dona',
    byCompany: 'Kompaniyalardan kirim',
    byCompanyHint: 'shu oyda, so’m',
    lines: '{n} qator',
    min: 'min',
    expected: 'kutilmoqda',
  },
  problems: {
    title: 'Muammolar',
    ok: 'Hozir muammo yo’q',
    okHint: 'Barcha navbatlar bo’sh. Ajoyib kun.',
    whatToDo: 'Nima qilish kerak',
    groups: {
      lowStock: 'Kam zaxira',
      lateShipments: 'Kechikkan yuklar',
      disputes: 'Ochiq nizolar',
      fees: 'Tasdiqlanmagan xizmat haqi',
      secondApproval: 'Qo’sh imzo kutayotgan to’lov',
      overpriced: 'Narx qoidasidan o’tmagan tovarlar',
      moderation: 'Moderatsiyada 24 soatdan uzoq',
    } as const,
    hints: {
      lowStock: 'Kompaniyaga yangi partiya buyurtma qiling yoki tovarni vaqtincha yashiring.',
      lateShipments: 'BTS bilan bog’laning, xaridorga muddat haqida xabar bering.',
      disputes: 'Operator 48 soat ichida qaror qilishi kerak: to’liq, qisman yoki rad.',
      fees: 'Moliya avtomatik haqni tasdiqlasin yoki o’zgartirsin.',
      secondApproval: '50 mln so’mdan yuqori to’lov — ikkinchi imzo kerak.',
      overpriced: 'Kompaniya narxni bozor darajasiga tushirsin, aks holda tovar yopiladi.',
      moderation: 'Moderator navbatni tozalasin — sotuvchi kutmoqda.',
    } as const,
    sla: 'SLA',
    slaLeft: '{h} soat qoldi',
    slaOver: '{h} soat o’tib ketdi',
    daysInTransit: '{n} kun yo’lda',
    left: 'qoldi',
  },
} as const

export type PeriodKey = keyof typeof D.period
export type TabKey = keyof typeof D.tabs
export type ProblemKey = keyof typeof D.problems.groups

export function tt(s: string, vars: Record<string, string | number>): string {
  return s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`))
}
