/**
 * Mobil ilovaga xos matnlar (o’zbek lotin). `@/i18n/uz` da bo’lmagan kalitlar shu yerda.
 */
export const ms = {
  onboarding: {
    skip: 'O’tkazib yuborish', next: 'Keyingi', start: 'Boshlash',
    slides: [
      { icon: 'badge-check', title: '«Narx tekshirilgan» nima?', body: 'Har e’lon narxi 30 kunlik bozor bilan solishtiriladi. Bu belgi — narx bozordan arzon va tekshirilgan degani.' },
      { icon: 'tag', title: 'Qanday sotiladi?', body: 'Rasm, IMEI va narxni kiritasiz. AI va narx tahlilchisi tekshiradi, sizga taklif keladi. Rozi bo’lsangiz — e’lon chiqadi.' },
      { icon: 'shield-check', title: 'Pul qanday himoyalanadi?', body: 'Xaridor to’lovi tovar sizga yetgunicha Sharabara himoyasida turadi. Tovarni olib tasdiqlaganingizdan keyin pul sotuvchiga o’tadi.' },
    ],
  },
  hint: {
    desktop: 'Telefon ko’rinishi. Haqiqiy qurilmada to’liq ekranda ochiladi.',
  },
  home: {
    regionAll: 'Hammasi',
    allRegions: 'Butun O’zbekiston',
    pickRegion: 'Viloyatni tanlang',
    yourRegion: 'Sizning viloyatingiz',
    heroTitle: 'Narx bilan yutamiz',
    heroSub: '{n} ta e’londa narx tekshirilgan',
    heroCta: 'Tekshirilganlarni ko’rish',
    verified: 'Narx tekshirilgan',
    verifiedSub: 'Bozor narxi bilan solishtirilgan',
    mallSub: 'Kompaniyalardan yangi tovarlar',
    fresh: 'Yangi e’lonlar',
    dropsSub: 'Sotuvchi narxni pasaytirdi',
    camera: 'Rasm bo’yicha qidirish',
    mallCta: 'Mall’ga o’tish',
    mallBannerTitle: 'Sharabara Mall',
    mallBannerSub: 'Kompaniyalardan yangi tovar · rasmiy kafolat · 1 kunda yetkazish',
    mixed: 'Lenta',
    official: 'Rasmiy',
    refresh: 'Yangilanmoqda…',
    pullHint: 'Yangilash uchun torting',
    noFeed: 'Lenta hozircha bo’sh',
    noFeedHint: 'E’lonlarni ko’rib chiqing — tavsiyalar shunga qarab shakllanadi.',
    generic: 'Sizga yoqishi mumkin',
  },
  search: {
    title: 'Qidiruv',
    models: 'Modellar',
    categories: 'Kategoriyalar',
    startTyping: 'Model, kategoriya yoki so’z kiriting',
    tracked: 'Qidiruv eslab qolindi',
  },
  catalog: {
    title: 'Katalog',
    filters: 'Filtrlar',
    condition: 'Holati',
    region: 'Viloyat',
    anyRegion: 'Barcha viloyatlar',
    sortLabel: 'Saralash',
    view: 'Ko’rinish',
    loadingMore: 'Yana yuklanmoqda…',
    end: 'Hammasi ko’rsatildi',
    emptyHint: 'Filtrlarni yumshating yoki boshqa kategoriyani tanlang.',
  },
  mall: {
    companies: 'Kompaniyalar',
    products: 'Tovarlar',
    promos: 'Aksiyalar',
    rating: 'reyting',
    sold: 'sotilgan',
    allProducts: 'Barcha tovarlar',
    storeCategories: 'Bo’limlar',
    about: 'Do’kon haqida',
    joined: 'Sharabara’da {n} oydan beri',
    lateShipments: 'kechikkan jo’natma',
    returnsRate: 'qaytarish',
  },
  listing: {
    gallery: 'Rasmlar',
    zoom: 'Kattalashtirish',
    description: 'Tavsif',
    details: 'Tafsilotlar',
    battery: 'Batareya',
    imei: 'IMEI',
    notFound: 'E’lon topilmadi',
    notFoundHint: 'Havola eskirgan yoki e’lon o’chirilgan bo’lishi mumkin.',
    soldNote: 'Bu e’lon sotilgan. O’xshash e’lonlarni ko’ring.',
    reservedNote: 'Bu e’lon band qilingan — xaridor to’lov qildi.',
    whySub: 'Sharabara tekshiruvi',
    sellerListings: 'Sotuvchining e’lonlari',
    verifiedSeller: 'Tasdiqlangan sotuvchi',
    priceNow: 'Hozirgi narx',
    priceWas: 'Avvalgi narx',
    added: 'Savatga qo’shildi',
    inCartGo: 'Savatga o’tish',
    stats: '{v} ko’rish · {s} saqlash',
    marketMedianNote: 'A-holatga keltirilgan o’rtacha narx',
    breakdownEmpty: 'Narx tahlili moderator tomonidan tasdiqlangan.',
    cheaperPct: 'bozordan {pct} arzon',
    fairNote: 'Narx tekshiruvi 30 kun ichidagi sotilgan va faol e’lonlar asosida.',
  },
  product: {
    qty: 'Miqdor',
    inStock: 'Omborda bor',
    outOfStock: 'Tugagan',
    warranty: 'Kafolat',
    returns: 'Qaytarish',
    shipping: 'Jo’natish',
    official: 'Rasmiy kafolat bilan',
    fromStore: 'Do’kondan',
    toStore: 'Do’konga o’tish',
    notFound: 'Tovar topilmadi',
  },
  chat: {
    list: 'Yozishmalar',
    empty: 'Hali yozishma yo’q',
    emptyHint: 'E’lon sahifasida «Yozish» tugmasini bosing.',
    you: 'Siz',
    send: 'Yuborish',
    aboutListing: 'E’lon haqida',
    readOnly: 'Bu yozishmada faqat xaridor va sotuvchi yoza oladi.',
  },
  cart: {
    seller: 'Sotuvchi',
    company: 'Kompaniya',
    shipment: '{n}-yuk',
    removed: 'Savatdan o’chirildi',
    goCatalog: 'Katalogga o’tish',
    subtotal: 'Tovarlar',
    deliveryCalc: 'Yetkazish rasmiylashtirishda hisoblanadi',
  },
  checkout: {
    title: 'Rasmiylashtirish',
    stepOf: '{i}/{n}',
    address: 'Manzil',
    addressPlaceholder: 'Ko’cha, uy, kvartira',
    pickupNote: 'Sharabara punkti: Toshkent, Yunusobod, Amir Temur ko’chasi 108. 09:00–20:00.',
    courierNote: 'Toshkent shahri bo’ylab 1 kun ichida, kuryer qo’ng’iroq qiladi.',
    chooseBranch: 'Filialni tanlang',
    locating: 'Aniqlanmoqda…',
    located: 'Joylashuv aniqlandi',
    mapOffline: 'Xarita oflayn — sxematik ko’rinish',
    branchesNear: 'Yaqin filiallar',
    selected: 'Tanlandi',
    payMethod: 'To’lov usuli',
    gatewayTitle: 'To’lov',
    gatewayAmount: 'To’lov summasi',
    gatewayNote: 'Demo: karta ma’lumotlari so’ralmaydi. Production’da Payme/Click oynasi ochiladi.',
    gatewayCash: 'Naqd to’lov filialda qabul qilinadi. Buyurtma hozir tasdiqlanadi.',
    payNow: 'Tasdiqlash',
    summary: 'Buyurtma tarkibi',
    items: 'Tovarlar',
    total: 'Jami',
    needBranch: 'Filialni tanlang',
    emptyCart: 'Savat bo’sh — rasmiylashtirish uchun tovar qo’shing.',
    branchLabel: 'BTS filiali',
    orderTotal: 'Buyurtma summasi',
    escrowShort: 'Himoyada',
  },
  orders: {
    detail: 'Buyurtma',
    items: 'Tovarlar',
    delivery: 'Yetkazish',
    payment: 'To’lov',
    seller: 'Sotuvchi',
    branch: 'Filial',
    noWaybill: 'Yuk xati qadoqlangandan keyin paydo bo’ladi',
    problemTitle: 'Muammo haqida xabar berish',
    problemDesc: 'Tavsif',
    problemDescPlaceholder: 'Nima bo’lganini qisqacha yozing',
    problemPhotos: 'Rasmlar',
    problemSend: 'So’rov yuborish',
    rateTitle: 'Xaridni baholang',
    rateComment: 'Izoh',
    ratePlaceholder: 'Sotuvchi va yetkazish haqida',
    rateSend: 'Baholash',
    rated: 'Rahmat! Bahoyingiz qabul qilindi.',
    yourRating: 'Sizning bahoyingiz',
    escrowHeld: 'Pul Sharabara’da saqlanmoqda',
    escrowReleased: 'Pul sotuvchiga o’tkazildi',
    escrowRefunded: 'Pul qaytarildi',
    active: 'Faol',
    done: 'Yakunlangan',
    problemSent: 'Muammo qayd etildi',
    smsCode: 'Olib ketish uchun SMS-kodni ko’rsating',
  },
  notif: {
    unread: '{n} ta o’qilmagan',
    allRead: 'Barchasi o’qilgan',
  },
  profile: {
    demoSwitch: 'Demo: foydalanuvchini almashtirish',
    demoSwitchHint: 'Xaridor ↔ sotuvchi',
    switched: 'Endi siz — {name}',
    savedListings: 'E’lonlar',
    savedProducts: 'Mall tovarlari',
    noSaved: 'Saqlanganlar yo’q',
    noSavedHint: 'Yurak belgisini bosib e’lonni saqlang.',
    noSearches: 'Saqlangan qidiruv yo’q',
    noSearchesHint: 'Qidiruv sahifasida «Qidiruvni saqlash» tugmasini bosing.',
    searchDeleted: 'Qidiruv o’chirildi',
    maxPrice: 'gacha',
    langNote: 'Ruscha tarjima production’da. Demo matnlari o’zbekcha.',
    langSaved: 'Til saqlandi',
    notifOn: 'Push bildirishnomalar',
    cashOn: 'Naqd to’lov imkoniyati',
    clearTitle: 'Tarixni tozalaysizmi?',
    clearDesc: 'Ko’rish va qidiruv tarixi o’chadi. «Siz uchun» bo’limi umumiy tavsiyalarga qaytadi.',
    deleteTitle: 'Akkauntni o’chirasizmi?',
    deleteDesc: 'Barcha e’lonlar, yozishmalar va buyurtmalar tarixi o’chiriladi.',
    deleteDemo: 'Demo rejimida akkaunt o’chirilmaydi. Production’da 30 kun ichida o’chiriladi.',
    helpTitle: 'Yordam',
    verified: 'Tasdiqlangan',
    member: 'A’zo',
    faq: [
      { q: '«Narx tekshirilgan» nimani anglatadi?', a: 'Sharabara AI va narx tahlilchisi e’lonni 30 kunlik bozor ma’lumotlari bilan solishtiradi. Belgi — narx bozordan kamida 5% arzon degani.' },
      { q: 'Pulim qanday himoyalanadi?', a: 'To’lov Sharabara himoyasida saqlanadi. Siz tovarni BTS filialidan olib, SMS-kod bilan tasdiqlaganingizdan keyin pul sotuvchiga o’tadi.' },
      { q: 'Yetkazish qancha vaqt oladi?', a: 'Sotuvchi tovarni Sharabara punktiga topshiradi, biz tekshirib qadoqlaymiz. BTS orqali viloyatlarga 1–3 kun.' },
      { q: 'Tovar tavsifga mos kelmasa?', a: 'Buyurtma sahifasida «Muammo bor» tugmasini bosing. Operator 24 soat ichida javob beradi, pul to’liq yoki qisman qaytariladi.' },
      { q: 'Sotuvchi sifatida qancha to’layman?', a: 'Xizmat haqi faqat tovar sotilganda olinadi — narxga qarab 2–5%. E’lon joylash bepul.' },
    ],
  },
  sell: {
    landingTitle: 'Sotmoqchimisiz?',
    landingSub: 'Rasm tashlang — AI modelni aniqlaydi, narx tahlilchisi adolatli narx taklif qiladi. E’lon joylash bepul.',
    start: 'E’lon joylash',
    how: 'Qanday ishlaydi',
    steps: ['Rasm va ma’lumot kiritasiz', 'AI 1 daqiqada tekshiradi', 'Narx taklifini olasiz', 'Sotilganda pul kartaga'],
    recent: 'Oxirgi e’lonlaringiz',
    samples: 'Namuna rasmlar',
    photosCount: '{n} / 4+',
    dragHint: 'Tartiblash uchun sudrang',
    remove: 'O’chirish',
    imeiInvalid: 'IMEI 15 raqamdan iborat bo’lishi kerak',
    titleRequired: 'Nomini kiriting',
    priceRequired: 'Narxni kiriting',
    photosRequired: 'Kamida 1 ta rasm kerak',
    categoryRequired: 'Kategoriyani tanlang',
    autoplay: 'Avtomatik to’ldirilmoqda…',
    submitting: 'Yuborilmoqda…',
    aiTitle: 'AI tahlili',
    aiSub: 'Rasm va matn asosida modelni, holatni va bozor narxini tekshiryapman',
    specs: 'Aniqlangan belgilar',
    specsHint: 'Xato bo’lsa, belgini bosib tuzating',
    model: 'Model', storage: 'Xotira', color: 'Rang', condition: 'Holati',
    toMyListings: 'E’lonlarim',
    offerFrom: 'Narx tahlilchisi taklifi',
    offerNote: 'Izoh',
    offerAsk: 'Siz so’ragan narx',
    offerAccepted: 'E’lon chiqdi',
    offerStatusOther: 'Bu e’lon uchun narx taklifi yo’q',
    confirmDecline: 'Taklifni rad etasizmi?',
    confirmDeclineDesc: 'E’lon chiqmaydi. Narxni o’zgartirib qayta yuborishingiz mumkin.',
    market: 'Bozor tahlili',
    comparables: '{n} ta o’xshash e’lon',
    confidence: 'Ishonch',
    my: {
      all: 'Hammasi', active: 'Faol', review: 'Tekshiruvda', offers: 'Takliflar', sold: 'Sotilgan', other: 'Boshqa',
      empty: 'E’lon yo’q', emptyHint: 'Birinchi e’loningizni joylang — bu bepul.',
      offer: 'Narx taklifi', boost: 'E’lonni ko’tarish', changePrice: 'Narxni o’zgartirish', remove: 'O’chirish', resubmit: 'Qayta yuborish',
      removeTitle: 'E’lonni o’chirasizmi?', removeDesc: 'E’lon lentadan yo’qoladi. Qayta tiklab bo’lmaydi.',
      removed: 'E’lon o’chirildi',
      priceChanged: 'Narx yangilandi',
      priceTitle: 'Yangi narx',
      boostTitle: 'E’lonni ko’tarish',
      boostSub: 'Tanlangan muddat davomida e’lon ro’yxat boshida turadi',
      boosted: 'E’lon ko’tarildi',
      views7: '7 kun',
      reason: 'Sabab',
      continue: 'Davom ettirish',
    },
  },
  wallet: {
    nextFriday: 'Keyingi to’lov: juma',
    card: 'HUMO •••• 1234',
    cardHint: 'To’lovlar shu kartaga tushadi',
    withdrawToast: 'Juma kuni avtomatik o’tkaziladi',
    noHistory: 'To’lovlar tarixi bo’sh',
    noHistoryHint: 'Birinchi savdo yakunlangach bu yerda ko’rinadi.',
    scheduled: 'Rejalashtirilgan',
    pending: 'Kutilmoqda',
    paid: 'To’langan',
    awaiting: 'Tasdiq kutilmoqda',
    escrowHint: 'Yetkazilgach va xaridor tasdiqlagach yechish mumkin',
    payoutFor: '{n} ta savdo',
  },
  common: {
    back: 'Orqaga',
    seeAll: 'Barchasi',
    showMore: 'Ko’proq',
    justNow: 'hozir',
    minAgo: '{n} daqiqa oldin',
    hourAgo: '{n} soat oldin',
    yesterday: 'kecha',
    daysAgo: '{n} kun oldin',
    km: '{n} km',
    demoUser: 'Demo foydalanuvchi',
    loadError: 'Ma’lumot yuklanmadi',
    notFound: 'Sahifa topilmadi',
    toHome: 'Bosh sahifaga',
    remove: 'O’chirish',
    edit: 'Tahrirlash',
    processing: 'Bajarilmoqda…',
    pcs: 'dona',
    star: 'yulduz',
  },
} as const
