import { forwardRef } from 'react'
import {
  Armchair, Baby, BadgeCheck, BadgePercent, Banknote, BarChart3, Bell, Bookmark, Building2, ChartColumn,
  Check, Clock, Clock3, Compass, CreditCard, Dices, Dumbbell, FileCheck, FileClock, FileSpreadsheet, FileText,
  Filter, Hand, Heart, History, Home, Inbox, Info, KeyRound, Laptop, LayoutDashboard, List, Lock, MapPin,
  Megaphone, MessageCircle, Monitor, Package, PackageOpen, PackageSearch, Percent, Phone, Pin, Receipt,
  RotateCcw, ScrollText, Search, SearchX, Send, ShieldCheck, Shirt, ShoppingBag, ShoppingCart, Smartphone,
  Sparkles, Stamp, Star, Store, Tag, TriangleAlert, Truck, Tv, User, Users, Wallet, Warehouse, WashingMachine,
  Circle, X, Plus, Minus, ChevronRight, ChevronLeft, ChevronDown, ChevronUp, ArrowRight, ArrowLeft, ArrowUp,
  ArrowDown, Trash2, Settings, CircleHelp, Copy, Printer, Download, Upload, Eye, RefreshCw, Calendar, Mail,
  ExternalLink, Zap, Box, Coins, Image, Camera, Layers, Moon, Sun, LogOut, Menu, Ellipsis, Pause, Play,
  Square, SkipForward, FastForward, Database, Globe, Flag, Gift, Award, Handshake, Briefcase, Calculator,
  Factory, Boxes, Link, MailCheck, BellRing, CircleCheck, CircleX, CircleAlert, Shield, Timer, Hourglass,
  Map, Navigation, Locate, Crosshair, Scan, ScanLine, QrCode, Barcode, FileDown, FileUp, Sheet, Table, Columns3,
  Rows3, SlidersHorizontal, ListFilter, Grid2x2, LayoutGrid, ArrowLeftRight, MessageSquare, UserCheck, UserX,
  Ban, ThumbsUp, ThumbsDown, Repeat, Undo2, Redo2, Save, Pencil, Pen, SquarePen, CheckCheck, ClipboardCheck,
  PackageCheck, PackageX, TruckElectric, Bus, Building, Landmark, WalletCards, HandCoins, PiggyBank, TrendingUp,
  TrendingDown, Activity, ChartLine, ChartBar, ChartPie, Gauge, Target, Flame, Sprout, Leaf, FolderTree, ZoomIn, ZoomOut,
} from 'lucide-react'
import type { LucideIcon, LucideProps } from 'lucide-react'

/** Faqat ilovada ishlatiladigan ikonlar — butun lucide to'plami (~600KB) bundle'ga kirmasin. */
const ICONS: Record<string, LucideIcon> = {
  'armchair': Armchair, Armchair,
  'baby': Baby, Baby,
  'badge-check': BadgeCheck, BadgeCheck,
  'badge-percent': BadgePercent, BadgePercent,
  'banknote': Banknote, Banknote,
  'bar-chart-3': BarChart3, BarChart3,
  'bell': Bell, Bell,
  'bookmark': Bookmark, Bookmark,
  'building-2': Building2, Building2,
  'chart-column': ChartColumn, ChartColumn,
  'check': Check, Check,
  'clock': Clock, Clock,
  'clock-3': Clock3, Clock3,
  'compass': Compass, Compass,
  'credit-card': CreditCard, CreditCard,
  'dices': Dices, Dices,
  'dumbbell': Dumbbell, Dumbbell,
  'file-check': FileCheck, FileCheck,
  'file-clock': FileClock, FileClock,
  'file-spreadsheet': FileSpreadsheet, FileSpreadsheet,
  'file-text': FileText, FileText,
  'filter': Filter, Filter,
  'hand': Hand, Hand,
  'heart': Heart, Heart,
  'history': History, History,
  'home': Home, Home,
  'inbox': Inbox, Inbox,
  'info': Info, Info,
  'key-round': KeyRound, KeyRound,
  'laptop': Laptop, Laptop,
  'layout-dashboard': LayoutDashboard, LayoutDashboard,
  'list': List, List,
  'lock': Lock, Lock,
  'map-pin': MapPin, MapPin,
  'megaphone': Megaphone, Megaphone,
  'message-circle': MessageCircle, MessageCircle,
  'monitor': Monitor, Monitor,
  'package': Package, Package,
  'package-open': PackageOpen, PackageOpen,
  'package-search': PackageSearch, PackageSearch,
  'percent': Percent, Percent,
  'phone': Phone, Phone,
  'pin': Pin, Pin,
  'receipt': Receipt, Receipt,
  'rotate-ccw': RotateCcw, RotateCcw,
  'scroll-text': ScrollText, ScrollText,
  'search': Search, Search,
  'search-x': SearchX, SearchX,
  'send': Send, Send,
  'shield-check': ShieldCheck, ShieldCheck,
  'shirt': Shirt, Shirt,
  'shopping-bag': ShoppingBag, ShoppingBag,
  'shopping-cart': ShoppingCart, ShoppingCart,
  'smartphone': Smartphone, Smartphone,
  'sparkles': Sparkles, Sparkles,
  'stamp': Stamp, Stamp,
  'star': Star, Star,
  'store': Store, Store,
  'tag': Tag, Tag,
  'triangle-alert': TriangleAlert, TriangleAlert,
  'truck': Truck, Truck,
  'tv': Tv, Tv,
  'user': User, User,
  'users': Users, Users,
  'wallet': Wallet, Wallet,
  'warehouse': Warehouse, Warehouse,
  'washing-machine': WashingMachine, WashingMachine,
  'circle': Circle, Circle,
  'x': X, X,
  'plus': Plus, Plus,
  'minus': Minus, Minus,
  'chevron-right': ChevronRight, ChevronRight,
  'chevron-left': ChevronLeft, ChevronLeft,
  'chevron-down': ChevronDown, ChevronDown,
  'chevron-up': ChevronUp, ChevronUp,
  'arrow-right': ArrowRight, ArrowRight,
  'arrow-left': ArrowLeft, ArrowLeft,
  'arrow-up': ArrowUp, ArrowUp,
  'arrow-down': ArrowDown, ArrowDown,
  'trash-2': Trash2, Trash2,
  'settings': Settings, Settings,
  'circle-help': CircleHelp, CircleHelp,
  'copy': Copy, Copy,
  'printer': Printer, Printer,
  'download': Download, Download,
  'upload': Upload, Upload,
  'eye': Eye, Eye,
  'refresh-cw': RefreshCw, RefreshCw,
  'calendar': Calendar, Calendar,
  'mail': Mail, Mail,
  'external-link': ExternalLink, ExternalLink,
  'zap': Zap, Zap,
  'box': Box, Box,
  'coins': Coins, Coins,
  'image': Image, Image,
  'camera': Camera, Camera,
  'layers': Layers, Layers,
  'moon': Moon, Moon,
  'sun': Sun, Sun,
  'log-out': LogOut, LogOut,
  'menu': Menu, Menu,
  'ellipsis': Ellipsis, Ellipsis,
  'pause': Pause, Pause,
  'play': Play, Play,
  'square': Square, Square,
  'skip-forward': SkipForward, SkipForward,
  'fast-forward': FastForward, FastForward,
  'database': Database, Database,
  'globe': Globe, Globe,
  'flag': Flag, Flag,
  'gift': Gift, Gift,
  'award': Award, Award,
  'handshake': Handshake, Handshake,
  'briefcase': Briefcase, Briefcase,
  'calculator': Calculator, Calculator,
  'factory': Factory, Factory,
  'boxes': Boxes, Boxes,
  'link': Link, Link,
  'mail-check': MailCheck, MailCheck,
  'bell-ring': BellRing, BellRing,
  'circle-check': CircleCheck, CircleCheck,
  'circle-x': CircleX, CircleX,
  'circle-alert': CircleAlert, CircleAlert,
  'shield': Shield, Shield,
  'timer': Timer, Timer,
  'hourglass': Hourglass, Hourglass,
  'map': Map, Map,
  'navigation': Navigation, Navigation,
  'locate': Locate, Locate,
  'crosshair': Crosshair, Crosshair,
  'scan': Scan, Scan,
  'scan-line': ScanLine, ScanLine,
  'qr-code': QrCode, QrCode,
  'barcode': Barcode, Barcode,
  'file-down': FileDown, FileDown,
  'file-up': FileUp, FileUp,
  'sheet': Sheet, Sheet,
  'table': Table, Table,
  'columns-3': Columns3, Columns3,
  'rows-3': Rows3, Rows3,
  'sliders-horizontal': SlidersHorizontal, SlidersHorizontal,
  'list-filter': ListFilter, ListFilter,
  'grid-2x2': Grid2x2, Grid2x2,
  'layout-grid': LayoutGrid, LayoutGrid,
  'arrow-left-right': ArrowLeftRight, ArrowLeftRight,
  'message-square': MessageSquare, MessageSquare,
  'user-check': UserCheck, UserCheck,
  'user-x': UserX, UserX,
  'ban': Ban, Ban,
  'thumbs-up': ThumbsUp, ThumbsUp,
  'thumbs-down': ThumbsDown, ThumbsDown,
  'repeat': Repeat, Repeat,
  'undo-2': Undo2, Undo2,
  'redo-2': Redo2, Redo2,
  'save': Save, Save,
  'pencil': Pencil, Pencil,
  'pen': Pen, Pen,
  'square-pen': SquarePen, SquarePen,
  'check-check': CheckCheck, CheckCheck,
  'clipboard-check': ClipboardCheck, ClipboardCheck,
  'package-check': PackageCheck, PackageCheck,
  'package-x': PackageX, PackageX,
  'truck-electric': TruckElectric, TruckElectric,
  'bus': Bus, Bus,
  'building': Building, Building,
  'landmark': Landmark, Landmark,
  'wallet-cards': WalletCards, WalletCards,
  'hand-coins': HandCoins, HandCoins,
  'piggy-bank': PiggyBank, PiggyBank,
  'trending-up': TrendingUp, TrendingUp,
  'trending-down': TrendingDown, TrendingDown,
  'activity': Activity, Activity,
  'chart-line': ChartLine, ChartLine,
  'chart-bar': ChartBar, ChartBar,
  'chart-pie': ChartPie, ChartPie,
  'gauge': Gauge, Gauge,
  'target': Target, Target,
  'flame': Flame, Flame,
  'sprout': Sprout, Sprout,
  'leaf': Leaf, Leaf,
  'folder-tree': FolderTree, FolderTree,
  'zoom-in': ZoomIn, ZoomIn,
  'zoom-out': ZoomOut, ZoomOut,
}

/** "shield-check" -> "ShieldCheck", "circle-2" -> "Circle2" */
export function kebabToPascal(name: string): string {
  return name
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

/** Resolve a lucide icon by kebab or Pascal name. Falls back to Circle. */
export function resolveIcon(name?: string | null): LucideIcon {
  if (!name) return Circle
  const direct = ICONS[name]
  if (direct) return direct
  const pascal = ICONS[kebabToPascal(name)]
  return pascal ?? Circle
}

export function hasIcon(name: string): boolean {
  return Boolean(ICONS[name] ?? ICONS[kebabToPascal(name)])
}

export interface IconProps extends Omit<LucideProps, 'ref'> {
  /** kebab-case lucide name, e.g. "shield-check" */
  name: string
}

/** <Icon name="smartphone" size={20} /> — lucide by kebab name, strokeWidth 1.75 default. */
export const Icon = forwardRef<SVGSVGElement, IconProps>(function Icon(
  { name, size = 20, strokeWidth = 1.75, ...rest },
  ref,
) {
  const Cmp = resolveIcon(name)
  return <Cmp ref={ref} size={size} strokeWidth={strokeWidth} aria-hidden={rest['aria-label'] ? undefined : true} {...rest} />
})

export type CategoryIconKey =
  | 'smartphone' | 'laptop' | 'tv' | 'washing-machine' | 'armchair' | 'shirt' | 'dumbbell' | 'baby'

export const CATEGORY_ICONS: Record<CategoryIconKey, LucideIcon> = {
  smartphone: Smartphone,
  laptop: Laptop,
  tv: Tv,
  'washing-machine': WashingMachine,
  armchair: Armchair,
  shirt: Shirt,
  dumbbell: Dumbbell,
  baby: Baby,
}

export type { LucideIcon }
