/** BTS hamkor paneli matnlari — o'zbek (lotin). Katta tugmalar, kam so'z. */
export const B = {
  title: 'BTS · Sharabara hamkor paneli',
  nav: { today: 'Bugungi partiya', shipments: 'Yuklar', branches: 'Filiallar', history: 'Tarix' },
  today: {
    eyebrow: 'Kechki partiya',
    packing: 'Sharabara hali qadoqlayapti — 17:00 da yopiladi',
    packingHint: 'Partiya yopilgach «Qabul qildim» tugmasi ochiladi.',
    closed: 'Partiya yopildi — olib ketishga tayyor',
    pickedUp: 'Partiya qabul qilindi',
    left: 'qoldi',
    count: 'Yuklar soni',
    byRegion: 'Viloyatlar bo’yicha',
    status: 'Holat',
    manifest: 'Manifest',
    acceptAll: 'Qabul qildim — hammasini',
    accepted: 'Qabul qilindi',
    acceptedSub: '{n} ta yuk yo’lga chiqdi',
    scan: 'Skanerlash',
    scanHint: 'Yuk xati raqamini kiriting yoki skanerlang',
    scanPlaceholder: 'BTS-2409-52310',
    scanBtn: 'Qabul qilish',
    scanOk: 'Yuk qabul qilindi',
    scanNotFound: 'Bu partiyada bunday yuk xati yo’q',
    scanAlready: 'Bu yuk allaqachon qabul qilingan',
    checklist: 'Yuk xatlari',
    ticked: '{a} / {n} qabul qilindi',
    noManifest: 'Bugun partiya yo’q',
    noManifestHint: 'Sharabara qadoqlashni boshlagach partiya shu yerda ko’rinadi.',
    closedAt: 'Yopilgan',
    pickedAt: 'Olib ketilgan',
    afterCutoff: '17:00 o’tdi — partiyani qabul qilish mumkin',
    statusOpen: 'Qadoqlanmoqda',
    statusClosed: 'Tayyor',
    statusPicked: 'Olib ketildi',
  },
  shipments: {
    all: 'Hammasi',
    buyer: 'Xaridor',
    branch: 'Filial',
    items: 'Tovar',
    atBranch: 'Filialga yetdi',
    delivered: 'Topshirildi',
    problem: 'Muammoli yuk',
    problemTitle: 'Muammoli yuk',
    problemDesc: 'Sabab yozing — Sharabara operatori ko’radi.',
    problemPh: 'Masalan: qadoq shikastlangan, manzil noto’g’ri…',
    problemSaved: 'Muammo qayd etildi',
    problemBadge: 'Muammo',
    empty: 'Yuk yo’q',
    emptyHint: 'Tanlangan holatda yuk topilmadi.',
    atBranchDone: 'Filialga yetdi — xaridorga SMS yuborildi',
    deliveredDone: 'Topshirildi — to’lov rejalashtirildi',
    count: '{n} ta yuk',
    region: 'Viloyat',
    noBranch: 'Filial belgilanmagan',
    courier: 'Toshkent kuryeri',
    pickup: 'O’zi olib ketadi',
  },
  branches: {
    search: 'Filial yoki viloyat',
    inTransit: 'Yo’lda',
    atBranch: 'Filialda',
    hours: 'Ish vaqti',
    empty: 'Filial topilmadi',
    total: '{n} ta filial',
  },
  history: {
    eyebrow: 'O’tgan partiyalar',
    empty: 'Tarix bo’sh',
    emptyHint: 'Qabul qilingan partiyalar shu yerda ko’rinadi.',
    shipments: '{n} ta yuk',
    shipmentsLabel: 'yuk',
    regions: '{n} viloyat',
    closed: 'Yopildi',
    picked: 'Qabul qilindi',
    delivered: 'Topshirildi',
    inProgress: 'Yo’lda / filialda',
  },
  common: { loading: 'Yuklanmoqda…', error: 'Xatolik yuz berdi', retry: 'Qayta urinish', cancel: 'Bekor qilish', save: 'Saqlash', today: 'Bugun', demoClock: 'Demo vaqt' },
} as const
