/** Kompaniya kabineti matnlari — o'zbek (lotin). */
export const P = {
  title: 'Kompaniya kabineti',
  eyebrow: 'Sharabara Mall · hamkor',
  switchCompany: 'Kompaniyani tanlash',
  nav: {
    overview: 'Umumiy ko’rinish',
    products: 'Tovarlar va zaxira',
    import: 'Excel orqali yuklash',
    orders: 'Buyurtmalar',
    promos: 'Aksiyalar',
    billing: 'Hisob-kitob',
    reports: 'Hisobotlar',
    api: 'API kalitlari',
    contract: 'Shartnoma va hujjatlar',
  },
  model: { wholesale: 'Ulgurji', warehouse: 'Sharabara ombori', self_ship: 'O’zi jo’natadi' },
  status: { active: 'Faol', onboarding: 'Ulanmoqda', suspended: 'To’xtatilgan' },
  overview: {
    salesMonth: 'Shu oy savdo',
    soldPcs: 'Sotilgan dona',
    nextPayout: 'Keyingi to’lov',
    overpriced: 'Narx qoidasidan o’tmagan',
    chart30: 'Oxirgi 30 kun savdosi',
    chartHint: 'Kunlik summa, so’m',
    recentOrders: 'So’nggi buyurtmalar',
    alerts: 'Diqqat',
    lowStock: 'Zaxira kam',
    lowStockHint: '{n} dona qoldi',
    noAlerts: 'Hammasi joyida',
    noAlertsHint: 'Zaxira yetarli, narxlar qoidaga mos.',
    openProducts: 'Tovarlarga o’tish',
    vsLastMonth: 'o’tgan oyga nisbatan',
    payoutDate: 'Juma, {d}',
    afterCommission: 'komissiyadan keyin',
    noPayout: 'Rejalashtirilgan to’lov yo’q',
  },
  products: {
    sku: 'SKU', product: 'Tovar', stock: 'Zaxira', price: 'Narx', market: 'Bozor o’rtachasi', check: 'Sharabara tekshiruvi',
    category: 'Kategoriya', warranty: 'Kafolat', views: 'Ko’rishlar',
    checkPassed: 'O’tdi', checkOver: 'Qimmat', checkPending: 'Tekshiruvda',
    search: 'SKU yoki nom bo’yicha qidirish',
    allCategories: 'Barcha kategoriyalar',
    allChecks: 'Barcha tekshiruvlar',
    lowStockOnly: 'Zaxira ≤ 5',
    editHint: 'Narx va zaxira katakchasini bosib tahrirlang · Enter — saqlash',
    priceSaved: 'Narx yangilandi',
    stockSaved: 'Zaxira yangilandi',
    nowOverpriced: 'Narx bozor o’rtachasidan yuqori — «Qimmat» belgisi qo’yildi',
    saveError: 'Saqlanmadi',
    details: 'Tovar tafsilotlari',
    description: 'Tavsif',
    returnDays: '{n} kun qaytarish',
    warrantyMonths: '{n} oy kafolat',
    createPromo: 'Aksiya yaratish',
    promoLabel: 'Aksiya nomi',
    promoDays: 'Davomiyligi (kun)',
    promoPrice: 'Aksiya narxi',
    promoCreated: 'Aksiya yaratildi',
    promoActive: 'Aksiya faol',
    promoUntil: '{d} gacha',
    empty: 'Tovar topilmadi',
    emptyHint: 'Filtrlarni o’zgartiring yoki Excel orqali tovar yuklang.',
    total: '{n} ta tovar',
    lowStockBadge: 'kam',
    priceTooLow: 'Narx 1 000 so’mdan kam bo’lmasin',
    priceTooHigh: 'Narx 500 mln so’mdan oshmasin',
  },
  import: {
    title: 'Excel orqali yuklash',
    lead: 'Tovarlar ro’yxatini .xlsx, .xls yoki .csv faylda yuklang. Ustunlarni o’zingiz moslashtirasiz.',
    drop: 'Faylni shu yerga tashlang',
    or: 'yoki',
    choose: 'Fayl tanlash',
    template: 'Shablon yuklab olish',
    sample: 'Namuna fayl bilan sinash',
    steps: ['Fayl', 'Ustunlar', 'Tekshiruv', 'Natija'],
    detected: '{rows} qator · {cols} ustun · «{sheet}» varag’i',
    mapTitle: 'Ustunlarni moslashtirish',
    mapLead: 'Har bir maydon uchun fayldagi ustunni tanlang. Yulduzchali maydonlar majburiy.',
    fields: { sku: 'SKU', title: 'Nomi', price: 'Narx (so’m)', stock: 'Zaxira', categoryId: 'Kategoriya', warrantyMonths: 'Kafolat (oy)', description: 'Tavsif' },
    notMapped: '— tanlanmagan —',
    guessed: 'avtomatik',
    preview: 'Ko’rib chiqish (birinchi 20 qator)',
    errors: 'Xatolar',
    noErrors: 'Xato topilmadi',
    errRow: '{n}-qator',
    errPriceEmpty: 'narx bo’sh',
    errPriceBad: 'narx noto’g’ri',
    errSkuEmpty: 'SKU bo’sh',
    errSkuDup: 'SKU takror',
    errTitleEmpty: 'nom bo’sh',
    errStockBad: 'zaxira noto’g’ri',
    excluded: 'Xatoli qatorlar yuklanmaydi',
    summary: '{add} ta tovar qo’shiladi, {upd} tasi yangilanadi',
    skipped: '{n} qator xato bilan o’tkazib yuboriladi',
    confirm: 'Tasdiqlash',
    back: 'Orqaga',
    next: 'Davom etish',
    uploading: 'Yuklanmoqda…',
    uploadingHint: 'Tovarlar tekshirilib, katalogga qo’shilmoqda',
    doneTitle: 'Yuklash yakunlandi',
    added: 'qo’shildi',
    updated: 'yangilandi',
    skippedShort: 'o’tkazildi',
    again: 'Yana yuklash',
    toProducts: 'Tovarlarni ko’rish',
    parseError: 'Faylni o’qib bo’lmadi',
    parseErrorHint: '.xlsx, .xls yoki .csv formatini tekshiring. Birinchi qator — ustun nomlari bo’lishi kerak.',
    needRequired: 'SKU, Nomi, Narx va Zaxira ustunlarini tanlang',
    templateName: 'sharabara-shablon.xlsx',
    sampleName: 'namuna-tovarlar.xlsx',
    dropHint: 'Bitta fayl, 5 MB gacha',
    fileLabel: 'Excel fayl tanlash',
  },
  orders: {
    id: 'Buyurtma', items: 'Tovarlar', subtotal: 'Summa', status: 'Holat', branch: 'Filial', waybill: 'Yuk xati', date: 'Sana', buyer: 'Xaridor',
    ready: 'Tayyor', handed: 'BTS’ga topshirdim',
    warehouseNote: 'Sharabara ombori qadoqlaydi', warehouseHint: 'Bu model bo’yicha tovar Sharabara omboridan jo’natiladi. Sizdan amal talab qilinmaydi.',
    readyDone: 'Buyurtma qadoqlandi, yuk xati yaratildi', handedDone: 'BTS’ga topshirildi',
    empty: 'Buyurtma yo’q', emptyHint: 'Tovarlaringiz sotilgach, buyurtmalar shu yerda ko’rinadi.',
    timeline: 'Holatlar tarixi', all: 'Hammasi', active: 'Faol', done: 'Yakunlangan',
    fee: 'Komissiya', net: 'Sizga tegadi', courier: 'Toshkent kuryeri', pickup: 'O’zi olib ketadi',
    total: '{n} ta buyurtma',
  },
  promos: {
    title: 'Aksiyalar', active: 'Faol aksiyalar', empty: 'Faol aksiya yo’q', emptyHint: 'O’ngdagi forma orqali birinchi aksiyani yarating.',
    create: 'Yangi aksiya', product: 'Tovar', pickProduct: 'Tovarni tanlang', oldPrice: 'Joriy narx', discount: 'Chegirma', ends: 'Tugaydi',
    labelPh: 'Masalan: Haftalik chegirma', created: 'Aksiya yaratildi', priceMustBeLower: 'Aksiya narxi joriy narxdan past bo’lishi kerak',
    daysLeft: '{n} kun qoldi', endsToday: 'Bugun tugaydi',
  },
  billing: {
    title: 'Hisob-kitob', payouts: 'To’lovlar', status: 'Holat', amount: 'Summa', scheduled: 'Rejalashtirilgan', paid: 'To’langan', orders: 'Buyurtmalar', card: 'Karta',
    payoutStatus: { pending: 'Kutilmoqda', scheduled: 'Rejalashtirildi', awaiting_second_approval: 'Ikkinchi tasdiq', paid: 'To’landi' },
    commission: 'Komissiya hisobi', rate: 'Komissiya stavkasi', salesMonth: 'Shu oy savdo', commissionSum: 'Komissiya', net: 'Sof tushum',
    akt: 'Akt-sverka', aktBtn: 'Akt-sverka', pdf: 'PDF yuklab olish', aktTitle: 'Hisob-kitob dalolatnomasi', aktPeriod: 'Davr', aktParties: 'Tomonlar',
    aktSharabara: 'Sharabara MCHJ', aktCompany: 'Hamkor', aktTable: { date: 'Sana', order: 'Buyurtma', item: 'Tovar', sum: 'Summa', fee: 'Komissiya', net: 'Sof' },
    aktTotal: 'Jami', aktSign1: 'Sharabara nomidan', aktSign2: 'Hamkor nomidan', aktSign: 'imzo', aktNote: 'Dalolatnoma elektron shaklda tuzilgan. Namuna hujjat.',
    empty: 'To’lovlar yo’q', emptyHint: 'Yetkazilgan buyurtmalar bo’yicha to’lovlar juma kunlari o’tkaziladi.',
    aktNo: 'Akt №',
  },
  reports: {
    title: 'Hisobotlar', byCategory: 'Kategoriya bo’yicha savdo', byCategoryHint: 'Oxirgi 30 kun, so’m',
    turnover: 'Zaxira aylanmasi', turnoverHint: '30 kunda sotilgan / mavjud zaxira', returns: 'Qaytarish darajasi', returnsHint: 'Qaytarilgan / yetkazilgan buyurtmalar',
    platformAvg: 'Platforma o’rtachasi', sold: 'Sotildi', inStock: 'Zaxirada', ratio: 'Aylanma', good: 'Yaxshi', slow: 'Sekin', noData: 'Ma’lumot yo’q',
    ordersDelivered: 'Yetkazilgan', ordersReturned: 'Qaytarilgan', yours: 'Sizning ko’rsatkichingiz',
  },
  api: {
    title: 'API kalitlari', lead: 'SAP, 1C yoki o’z tizimingizni ulash uchun. Kalit faqat bir marta ko’rsatiladi.',
    newKey: 'Yangi kalit', label: 'Nomi', labelPh: 'Masalan: 1C sinxronizatsiya', prefix: 'Prefiks', created: 'Yaratilgan', lastUsed: 'So’nggi ishlatilgan', never: 'Hali ishlatilmagan',
    revoked: 'Bekor qilingan', active: 'Faol', revoke: 'Bekor qilish', revokeTitle: 'Kalitni bekor qilasizmi?', revokeDesc: 'Bu kalit bilan ishlaydigan integratsiyalar to’xtaydi. Amalni qaytarib bo’lmaydi.',
    revokedToast: 'Kalit bekor qilindi', createdToast: 'Kalit yaratildi',
    secretTitle: 'Yangi kalit tayyor', secretWarn: 'Bu kalit faqat hozir ko’rsatiladi. Nusxa olib, xavfsiz joyda saqlang — keyin qayta ko’rib bo’lmaydi.',
    copy: 'Nusxa olish', copied: 'Nusxa olindi', done: 'Saqladim',
    docs: 'Endpointlar', docsLead: 'Barcha so’rovlar `Authorization: Bearer <kalit>` sarlavhasi bilan yuboriladi. Summalar so’mda, butun son.',
    webhook: 'Webhook', webhookLead: 'Buyurtma holati o’zgarganda Sharabara sizning URL manzilingizga POST yuboradi.',
    empty: 'Kalit yo’q', emptyHint: '«Yangi kalit» tugmasi orqali birinchi kalitni yarating.',
  },
  contract: {
    title: 'Shartnoma va hujjatlar', profile: 'Kompaniya profili', inn: 'STIR (INN)', model: 'Hamkorlik modeli', commission: 'Komissiya', joined: 'Ulangan sana', rating: 'Reyting', status: 'Holat',
    contractFile: 'Shartnoma fayli', notUploaded: 'Yuklanmagan', upload: 'Fayl yuklash', replace: 'Almashtirish', uploaded: 'Fayl saqlandi',
    docs: 'Hujjatlar', view: 'Ko’rish', docList: { contract: 'Shartnoma', akt: 'Akt-sverka · avgust', annex: 'Ilova №1 · komissiya jadvali' },
    docKinds: { contract: 'Asosiy hujjat', akt: 'Oylik hisobot', annex: 'Shartnomaga ilova' },
    preview: 'Hujjat ko’rinishi', previewNote: 'Namuna hujjat. Haqiqiy shartnoma matni emas.',
    signed: 'Imzolangan', pages: '{n} bet',
  },
  common: {
    save: 'Saqlash', cancel: 'Bekor qilish', close: 'Yopish', loading: 'Yuklanmoqda…', error: 'Xatolik yuz berdi', retry: 'Qayta urinish',
    today: 'Bugun', pcs: 'dona', csv: 'CSV eksport', filters: 'Filtrlar', clear: 'Tozalash', more: 'Batafsil',
  },
} as const
